import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomePage from "../componenrs/home/ui";
import Navbar from "../componenrs/navbar/Navbar";
const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Navbar />
				<HomePage />
			</main>
		</div>
	);
};

export default Home;
